GET http://localhost:3000/products

###

GET http://localhost:3000/products?name=rgb


###

GET http://localhost:3000/products/dbcc7332-a271-471e-b399-cc3a0dec8574

###

POST http://localhost:3000/products
Authorization: Bearer ad5474797a77e7eea816da8d6c8e58e2
Content-Type: application/json

{
  "name": "Mechanic Keyboard",
  "category": "Computer Accessories",
  "price": 500
}


###

PATCH http://localhost:3000/products/dbcc7332-a271-471e-b399-cc3a0dec8574
Authorization: Bearer ad5474797a77e7eea816da8d6c8e58e2
Content-Type: application/json

{
  "name": "TV",
  "category": "Electronics",
  "price": 2000
}

###

DELETE  http://localhost:3000/products/dbcc7332-a271-471e-b399-cc3a0dec8574
Authorization: Bearer ad5474797a77e7eea816da8d6c8e58e2

###

POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "username": "admin"
}

###

POST http://localhost:3000/auth/logout
Content-Type: application/json

{
  "token": "ad5474797a77e7eea816da8d6c8e58e2"
}